# Generated by Django 5.1.7 on 2025-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo_traducido',
            field=models.URLField(blank=True, null=True),
        ),
    ]
