# Generated by Django 5.1.7 on 2025-05-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_archivo_traducido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='archivo_traducido',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='idioma_destino',
        ),
    ]
